service: bookstore-serverless

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    MONGO_URI: ${env:MONGO_URI, "mongodb+srv://kyawmin7674:0lZW9cwTta0cqUR9@cluster0.f0ikhru.mongodb.net/test"}

functions:
  app:
    handler: lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 3000
